# Prob 9.4

try:
    raise OopsException()

except:
    print('Caught an oops')
